Fix dependency (#18)
We recently received the following error in the lambbda
cloudwatch logs..

```
Runtime.ImportModuleError: Unable to import module 'app':
cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_'
```

This seems like a library conflict between botocore and urllib3
so we update according to workaround proposed at these locations:

* https://stackoverflow.com/questions/76414514/cannot-import-name-default-ciphers-from-urllib3-util-ssl-on-aws-lambda-us
* https://github.com/boto/botocore/issues/2926
* https://github.com/psf/requests/issues/6432